/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as adminRouteRouteImport } from './routes/(admin)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as adminUsersIndexRouteImport } from './routes/(admin)/users/index'
import { Route as adminRolesIndexRouteImport } from './routes/(admin)/roles/index'
import { Route as adminPermissionsIndexRouteImport } from './routes/(admin)/permissions/index'
import { Route as adminDashboardIndexRouteImport } from './routes/(admin)/dashboard/index'

const adminRouteRoute = adminRouteRouteImport.update({
  id: '/(admin)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const adminUsersIndexRoute = adminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => adminRouteRoute,
} as any)
const adminRolesIndexRoute = adminRolesIndexRouteImport.update({
  id: '/roles/',
  path: '/roles/',
  getParentRoute: () => adminRouteRoute,
} as any)
const adminPermissionsIndexRoute = adminPermissionsIndexRouteImport.update({
  id: '/permissions/',
  path: '/permissions/',
  getParentRoute: () => adminRouteRoute,
} as any)
const adminDashboardIndexRoute = adminDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => adminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof adminRouteRouteWithChildren
  '/dashboard': typeof adminDashboardIndexRoute
  '/permissions': typeof adminPermissionsIndexRoute
  '/roles': typeof adminRolesIndexRoute
  '/users': typeof adminUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof adminRouteRouteWithChildren
  '/dashboard': typeof adminDashboardIndexRoute
  '/permissions': typeof adminPermissionsIndexRoute
  '/roles': typeof adminRolesIndexRoute
  '/users': typeof adminUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(admin)': typeof adminRouteRouteWithChildren
  '/(admin)/dashboard/': typeof adminDashboardIndexRoute
  '/(admin)/permissions/': typeof adminPermissionsIndexRoute
  '/(admin)/roles/': typeof adminRolesIndexRoute
  '/(admin)/users/': typeof adminUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dashboard' | '/permissions' | '/roles' | '/users'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/permissions' | '/roles' | '/users'
  id:
    | '__root__'
    | '/'
    | '/(admin)'
    | '/(admin)/dashboard/'
    | '/(admin)/permissions/'
    | '/(admin)/roles/'
    | '/(admin)/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  adminRouteRoute: typeof adminRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(admin)': {
      id: '/(admin)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof adminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/users/': {
      id: '/(admin)/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof adminUsersIndexRouteImport
      parentRoute: typeof adminRouteRoute
    }
    '/(admin)/roles/': {
      id: '/(admin)/roles/'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof adminRolesIndexRouteImport
      parentRoute: typeof adminRouteRoute
    }
    '/(admin)/permissions/': {
      id: '/(admin)/permissions/'
      path: '/permissions'
      fullPath: '/permissions'
      preLoaderRoute: typeof adminPermissionsIndexRouteImport
      parentRoute: typeof adminRouteRoute
    }
    '/(admin)/dashboard/': {
      id: '/(admin)/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof adminDashboardIndexRouteImport
      parentRoute: typeof adminRouteRoute
    }
  }
}

interface adminRouteRouteChildren {
  adminDashboardIndexRoute: typeof adminDashboardIndexRoute
  adminPermissionsIndexRoute: typeof adminPermissionsIndexRoute
  adminRolesIndexRoute: typeof adminRolesIndexRoute
  adminUsersIndexRoute: typeof adminUsersIndexRoute
}

const adminRouteRouteChildren: adminRouteRouteChildren = {
  adminDashboardIndexRoute: adminDashboardIndexRoute,
  adminPermissionsIndexRoute: adminPermissionsIndexRoute,
  adminRolesIndexRoute: adminRolesIndexRoute,
  adminUsersIndexRoute: adminUsersIndexRoute,
}

const adminRouteRouteWithChildren = adminRouteRoute._addFileChildren(
  adminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  adminRouteRoute: adminRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
