[package]
name = "app"
version = "0.1.0"
edition = "2024"

[dependencies]
lib = { path = "../lib" }
config = { path = "../config" }
axum.workspace = true
tokio.workspace = true
serde.workspace = true
anyhow.workspace = true
serde_json.workspace = true
sqlx.workspace = true