[package]
name = "utils"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { path = "../common" }
serde.workspace = true
serde_json.workspace = true
axum.workspace = true
sqlx-paginated.workspace = true